create database UNOESC_BANK;

USE UNOESC_BANK;

CREATE TABLE CLIENTE(ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
NOME VARCHAR(255)
);

CREATE TABLE CONTA( ID INT NOT NULL auto_increment primary KEY,
NRO_CONTA VARCHAR(10) NOT NULL, ID_CLIENTE INT NOT NULL,
CONSTRAINT FK_ID_CLIENTE_CONTA
    FOREIGN KEY (ID_CLIENTE)
	references CLIENTE(ID)
    );
    

