create database UNOESC_BANK;

USE UNOESC_BANK;

CREATE TABLE CLIENTE(ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
NOME VARCHAR(255)
);

CREATE TABLE CONTA( ID INT NOT NULL auto_increment primary KEY,
NRO_CONTA VARCHAR(10) NOT NULL, ID_CLIENTE INT NOT NULL,
CONSTRAINT FK_ID_CLIENTE_CONTA
    FOREIGN KEY (ID_CLIENTE)
	references CLIENTE(ID)
    );
    
create table transacao (
  ID INT NOT NULL auto_increment primary key, 
  ID_CONTA INT NOT NULL,
  TIPO_TRANSACAO INT NOT NULL,
  DATA_HORA DATETIME NOT NULL,
  VALOR FLOAT NOT NULL
);
    
-- DEFININDO UM FK POSTERIORMENTE A CRIAÇÃO DA TABELA
ALTER table TRANSACAO 
ADD FOREIGN KEY (ID_CONTA)
references CONTA(ID);

-- CRIANDO ÍNDICES
CREATE index IDX_TRANSACAO_TP_TRANSACAO
ON TRANSACAO (TIPO_TRANSACAO);

create index IDX_TRANSACAO_DATA_HORA
ON TRANSACAO (DATA_HORA);

