CREATE DATABASE UNOESC_PETS;

USE UNOESC_PETS;

CREATE TABLE TIPO_ANIMAL(ID INT NOT NULL auto_increment PRIMARY KEY,
NOME VARCHAR(255)
);

CREATE TABLE ANIMAL( ID INT NOT NULL auto_increment primary KEY,
 NOME VARCHAR(50) NOT NULL, 
 ID_TIPO_ANIMAL INT NOT NULL,
 DATA_NASCIMETO DATE NOT NULL,
 COR varchar(10) NOT NULL,
 PESO FLOAT NOT NULL, 
 ALTURA FLOAT NOT NULL,
 
 constraint FK_TD_ANIMAL_TIPO_ANIMAL
	foreign key (ID_TIPO_ANIMAL)
    references TIPO_ANIMAL(ID)
    );
    
CREATE TABLE VACINAÇÃO(
ID INT NOT NULL auto_increment primary KEY
NOME VARCHAR     

